const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  scanMods: (knownPath) => ipcRenderer.invoke('dialog:openFolder', knownPath),
  createProject: (projectData) => ipcRenderer.invoke('create-project', projectData),
  getGameVersions: () => ipcRenderer.invoke('get-game-versions'),
  searchModsOnline: (query, gameVersion, loader, sortBy, category) => ipcRenderer.invoke('search-mods-online', query, gameVersion, loader, sortBy, category),
  getModVersions: (projectId, gameVersion, loader, source) => ipcRenderer.invoke('get-mod-versions', projectId, gameVersion, loader, source),
  downloadMod: (versionObj, packPath) => ipcRenderer.invoke('download-mod', versionObj, packPath),
  installModRecursively: (versionId, gameVersion, loader, packPath) => ipcRenderer.invoke('install-mod-recursively', versionId, gameVersion, loader, packPath),
  diagnoseModpack: (packPath) => ipcRenderer.invoke('diagnose-modpack', packPath),
  exportModpack: (packPath, packName) => ipcRenderer.invoke('export-modpack', packPath, packName),
  deleteFile: (filePath, packPath) => ipcRenderer.invoke('delete-file', filePath, packPath),
  readFullFile: (filePath, packPath) => ipcRenderer.invoke('read-full-file', filePath, packPath),
  writeFile: (filePath, packPath, content) => ipcRenderer.invoke('write-file', filePath, packPath, content),
  openExternalEditor: (filePath, packPath) => ipcRenderer.invoke('open-external-editor', filePath, packPath),
  listFolderContent: (folderPath, packPath) => ipcRenderer.invoke('list-folder-content', folderPath, packPath),
  exploreJarContents: (jarName, packPath) => ipcRenderer.invoke('explore-jar-contents', jarName, packPath),
  readJarFile: (jarName, internalPath, packPath) => ipcRenderer.invoke('read-jar-file', jarName, internalPath, packPath),
  injectSpawnControl: (tweakData, packPath) => ipcRenderer.invoke('inject-spawn-control', tweakData, packPath),
  lootEditorApply: (packPath, lootPath, patch) => ipcRenderer.invoke('loot-editor-apply', packPath, lootPath, patch),
  scanModIds: (modsPath) => ipcRenderer.invoke('scan-mod-ids', modsPath),
  injectItemTweak: (tweakData, packPath) => ipcRenderer.invoke('inject-item-tweak', tweakData, packPath),
  optimizationStart: (packPath, categories) => ipcRenderer.invoke('optimization:start', packPath, categories),
  optimizationRollback: (packPath) => ipcRenderer.invoke('optimization:rollback', packPath),
  optimizationCheckStatus: (packPath) => ipcRenderer.invoke('optimization:check-status', packPath),
  injectEntityTweak: (tweakData, packPath) => ipcRenderer.invoke('inject-entity-tweak', tweakData, packPath),
  getScriptsTree: (packPath) => ipcRenderer.invoke('scripts:get-tree', packPath),
  readScript: (filePath, packPath) => ipcRenderer.invoke('scripts:read', filePath, packPath),
  saveScript: (filePath, content, packPath) => ipcRenderer.invoke('scripts:save', filePath, content, packPath),
  getSystemSpecs: () => ipcRenderer.invoke('get-system-specs'),
  calculateAllImpacts: (packPath) => ipcRenderer.invoke('calculate-all-impacts', packPath),
});
